service: import-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    ACCESS_ID: ${env:ACCESS_ID}
    SECRET: ${env:SECRET}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::import-service-store/*"
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::import-service-store/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: "arn:aws:sqs:${aws:region}:${aws:accountId}:catalog-items-queue"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          authorizer:
            name: authorization-service-${sls:stage}-basicAuthorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:authorization-service-${sls:stage}-basicAuthorizer
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-service-store
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    GatewayResponse401:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'*'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
        ResponseType: UNAUTHORIZED
        RestApiId: xiql988moj
        StatusCode: '401'
    GatewayResponse403:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'*'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
        ResponseType: DEFAULT_4XX
        RestApiId: xiql988moj
        StatusCode: '403'