service: import-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    ACCESS_ID: ${env:ACCESS_ID}
    SECRET: ${env:SECRET}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::import-service-store/*"
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::import-service-store/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: "arn:aws:sqs:us-east-1:637998571991:catalog-items-queue"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-service-store
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true